// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type County struct {
	ID            string
	Name          string
	CountyGivenID string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type SubCounty struct {
	ID        string
	Name      string
	CountyID  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Ward struct {
	ID          string
	Name        string
	SubCountyID string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
